### ISSUE TITLE
Colocar um readme com orientações rápidas de como usar

### ISSUE THREAD

**Issue by robotenique** [GreaterNumbersLaw/website#13]
Seria bom colocar no readme qual arquivo abrir e qual navegador usar , além da nossa identificação :top:

**Comment by pedro823** [comment]
vê se ficou um pouco melhor
A gente ainda pode botar nosso nome lá, mas ainda não fiz isso

**Comment by robotenique** [comment]
Tá ótimo, quando a gente for entregar a gnt coloca os nomes :ok_hand:
