### ISSUE TITLE
Add start/stop button to graph

### ISSUE THREAD

**Issue by pedro823** [GreaterNumbersLaw/website#8]
Adding a start/stop button to both dice and coin graphs would be nice.

**Comment by robotenique** [comment]
n é trivial ñ hein

**Comment by pedro823** [comment]
não precisa ser continuar daonde parou, pode ser um botão que para o gráfico e que se pressionado de novo ele reinicia
que nem voce tava fazendo no começo

**Comment by robotenique** [comment]
Aí é trivial

**Comment by pedro823** [comment]
Eu inclui o botão agora, mas a função startStop() no randomDice.js não tá no escopo do window.onload do diceGraph.js ou coinGraph.js, então ele consegue parar o gráfico mas não consegue mandar restartar de novo. Se você conseguir fazer isso funcionar, vai ser uma _beleza_

**Comment by robotenique** [comment]
Acho que pra desbugar vamos ter que tirar os iframes, não tenho controle do escopo e nem das funções direito quando eu rodo o jquery dentro do iframe...  :face_with_head_bandage:  :top:

**Comment by robotenique** [comment]
Se quiser eu tiro dos iframes e crio 2 páginas separadas pra cada gráfico (assim também dá pra ajustar a legenda pro caso da moeda), então cada arquivo fica em um escopo separado e o jquery vai ter full control sobre o objeto 'document'.

**Comment by robotenique** [comment]
E daí a index.html deixa de existir e ficamos só com dicegraph.html + coingraph.html

**Comment by pedro823** [comment]
Se não tiver como, sussa, não tem problema recarregar a pagina pra isso
A gente só precisa definir que o index tem que redirecionar pra alguma dessas duas, acho que a dice

**Comment by robotenique** [comment]
ta ok
